##
#  Data about all known objects.
#  Each key is the name of an object, in all lowercase.
#  Each value is an array with information about that object.
#  * First element is the name. This ideally matches the name of a Pikipedia article.
#  * Second is a generic, human-friendly type ("ene", "pla", etc.).
#  * Third is disambiguation modifiers, like how the Figworts have small and large variants.

# TODO These are the US names -- check EU and JP

OBJECTS = {
    "armor"            : ["Cloaking Burrow-nit",         "ene", ""           ],
    "baby"             : ["Bulborb Larva",               "ene", ""           ],
    "bigfoot"          : ["Raging Long Legs",            "ene", ""           ],
    "bigtreasure"      : ["Titan Dweevil",               "ene", ""           ],
    "blackman"         : ["Waterwraith",                 "ene", ""           ],
    "blackpom"         : ["Violet Candypop Bud",         "pla", ""           ],
    "bluechappy"       : ["Orange Bulborb",              "ene", ""           ],
    "bluekochappy"     : ["Dwarf Orange Bulborb",        "ene", ""           ],
    "bluepom"          : ["Lapis Lazuli Candypop Bud",   "pla", ""           ],
    "bomb"             : ["Bomb-rock",                   "obs", ""           ],
    "bombotakara"      : ["Volatile Dweevil",            "ene", ""           ],
    "bombsarai"        : ["Careening Dirigibug",         "ene", ""           ],
    "catfish"          : ["Water Dumple",                "ene", ""           ],
    "chappy"           : ["Red Bulborb",                 "ene", ""           ],
    "chiyogami"        : ["Chigoyami paper",             "oth", ""           ],
    "clover"           : ["Clover",                      "pla", ""           ],
    "daiodogreen"      : ["Glowstem",                    "pla", "green"      ],
    "daiodored"        : ["Glowstem",                    "pla", "red"        ],
    "damagumo"         : ["Beady Long Legs",             "ene", ""           ],
    "dangomushi"       : ["Segmented Crawbster",         "ene", ""           ],
    "demon"            : ["Bumbling Snitchbug",          "ene", ""           ],
    "egg"              : ["Egg",                         "oth", ""           ],
    "elecbug"          : ["Anode Beetle",                "ene", ""           ],
    "elechiba"         : ["Electrical wire",             "obs", ""           ],
    "elecotakara"      : ["Anode Dweevil",               "ene", ""           ],
    "fart"             : ["Doodlebug",                   "ene", ""           ],
    "firechappy"       : ["Fiery Bulblax",               "ene", ""           ],
    "fireotakara"      : ["Fiery Dweevil",               "ene", ""           ],
    "fkabuto"          : ["Armored Cannon Beetle Larva", "ene", "buried"     ],
    "fminihoudai"      : ["Gatling Groink",              "ene", "pedestal"   ],
    "frog"             : ["Yellow Wollywog",             "ene", ""           ],
    "fuefuki"          : ["Antenna Beetle",              "ene", ""           ],
    "gashiba"          : ["Gas pipe",                    "obs", ""           ],
    "gasotakara"       : ["Munge Dweevil",               "ene", ""           ],
    "hana"             : ["Creeping Chrysanthemum",      "ene", ""           ],
    "hanachirashi"     : ["Withering Blowhog",           "ene", ""           ],
    "hiba"             : ["Fire geyser",                 "obs", ""           ],
    "hikarikinoko"     : ["Common Glowcap",              "pla", ""           ],
    "houdai"           : ["Man-at-Legs",                 "ene", ""           ],
    "imomushi"         : ["Ravenous Whiskerpillar",      "ene", ""           ],
    "jigumo"           : ["Hermit Crawmad",              "ene", ""           ],
    "kabuto"           : ["Armored Cannon Beetle Larva", "ene", "surface"    ],
    "kareooinu_l"      : ["Figwort",                     "pla", "large brown"],
    "kareooinu_s"      : ["Figwort",                     "pla", "small brown"],
    "kingchappy"       : ["Emperor Bulblax",             "ene", ""           ],
    "kochappy"         : ["Dwarf Red Bulborb",           "ene", ""           ],
    "kogane"           : ["Iridescent Flint Beetle",     "ene", ""           ],
    "kumachappy"       : ["Spotty Bulbear",              "ene", ""           ],
    "kumakochappy"     : ["Dwarf Bulbear",               "ene", ""           ],
    "kurage"           : ["Lesser Spotted Jellyfloat",   "ene", ""           ],
    "leafchappy"       : ["Bulbmin",                     "ene", ""           ],
    "mar"              : ["Puffy Blowhog",               "ene", ""           ],
    "magaret"          : ["Margaret",                    "pla", ""           ],
    "marofrog"         : ["Wollywog",                    "ene", ""           ],
    "minihoudai"       : ["Gatling Groink",              "ene", "free"       ],
    "miulin"           : ["Mamuta",                      "ene", ""           ],
    "nekojarashi"      : ["Foxtail",                     "pla", ""           ],
    "onikurage"        : ["Greater Spotted Jellyfloat",  "ene", ""           ],
    "oopanmodoki"      : ["Giant Breadbug",              "ene", ""           ],
    "ooinu_l"          : ["Figwort",                     "pla", "large red"  ],
    "ooinu_s"          : ["Figwort",                     "pla", "small red"  ],
    "panmodoki"        : ["Breadbug",                    "ene", ""           ],
    "pelplant"         : ["Pellet Posy",                 "pla", ""           ],
    "queen"            : ["Empress Bulblax",             "ene", ""           ],
    "qurione"          : ["Honeywisp",                   "ene", ""           ],
    "randpom"          : ["Queen Candypop Bud",          "pla", ""           ],
    "redpom"           : ["Crimson Candypop Bud",        "pla", ""           ],
    "rkabuto"          : ["Decorated Cannon Beetle",     "ene", ""           ],
    "rock"             : ["Boulder",                     "obs", ""           ],
    "sarai"            : ["Swooping Snitchbug",          "ene", ""           ],
    "shijimichou"      : ["Unmarked Spectralids",        "ene", "group of 9" ],
    "snakecrow"        : ["Burrowing Snagret",           "ene", ""           ],
    "snakewhole"       : ["Pileated Snagret",            "ene", ""           ],
    "sokkuri"          : ["Skitter Leaf",                "ene", ""           ],
    "tadpole"          : ["Wogpole",                     "ene", ""           ],
    "tamagomushi"      : ["Mitite",                      "ene", ""           ],
    "tank"             : ["Fiery Blowhog",               "ene", ""           ],
    "tanpopo"          : ["Dandelion",                   "pla", ""           ],
    "tobi"             : ["Shearwig",                    "ene", ""           ],
    "tukushi"          : ["Horsetail",                   "pla", ""           ],
    "ujia"             : ["Female Sheargrub",            "ene", ""           ],
    "ujib"             : ["Male Sheargrub",              "ene", ""           ],
    "umimushi"         : ["Ranging Bloyster",            "ene", ""           ],
    "umimushiblind"    : ["Toady Bloyster",              "ene", ""           ],
    "wakame_l"         : ["Shoot",                       "pla", "large"      ],
    "wakame_s"         : ["Shoot",                       "pla", "small"      ],
    "watage"           : ["Seeding Dandelion",           "pla", ""           ],
    "waterotakara"     : ["Caustic Dweevil",             "ene", ""           ],
    "wealthy"          : ["Iridescent Glint Beetle",     "ene", ""           ],
    "whitepom"         : ["Ivory Candypop Bud",          "pla", ""           ],
    "wtank"            : ["Watery Blowhog",              "ene", ""           ],
    "xmas_item"        : ["Essential Furnishing",        "tre", ""           ],
    "yellowchappy"     : ["Hairy Bulborb",               "ene", ""           ],
    "yellowkochappy"   : ["Snow Bulborb",                "ene", ""           ],
    "yellowpom"        : ["Golden Candypop Bud",         "pla", ""           ],
    "zenmai"           : ["Fiddlehead",                  "pla", ""           ],
    "ahiru"            : ["Rubber Ugly",                 "tre", ""           ],
    "ahiru_head"       : ["Paradoxical Enigma",          "tre", ""           ],
    "akagai"           : ["Fortified Delicacy",          "tre", ""           ],
    "apple"            : ["Insect Condo",                "tre", ""           ],
    "apple_blue"       : ["Meat Satchel",                "tre", ""           ],
    "badminton"        : ["Air Brake",                   "tre", ""           ],
    "bane"             : ["Coiled Launcher",             "tre", ""           ],
    "bane_blue"        : ["Extreme Perspirator",         "tre", ""           ],
    "bane_red"         : ["Master's Instrument",         "tre", ""           ],
    "bane_yellow"      : ["Pilgrim Bulb",                "tre", ""           ],
    "baum_kuchen"      : ["Confection Hoop",             "tre", ""           ],
    "baum_kuchen_s"    : ["Pastry Wheel",                "tre", ""           ],
    "be_dama_blue"     : ["Mirth Sphere",                "tre", ""           ],
    "be_dama_blue_l"   : ["Crystallized Clairvoyance",   "tre", ""           ],
    "be_dama_red"      : ["Omniscient Sphere",           "tre", ""           ],
    "be_dama_red_l"    : ["Crystallized Telepathy",      "tre", ""           ],
    "be_dama_yellow"   : ["Love Sphere",                 "tre", ""           ],
    "be_dama_yellow_l" : ["Crystallized Telekinesis",    "tre", ""           ],
    "bell"             : ["Maternal Sculpture",          "tre", ""           ],
    "bell_blue"        : ["Sulking Antenna",             "tre", ""           ],
    "bell_red"         : ["Danger Chime",                "tre", ""           ],
    "bell_yellow"      : ["Spouse Alert",                "tre", ""           ],
    "bey_goma"         : ["Stupendous Lens",             "tre", ""           ],
    "bird_hane"        : ["Leviathan Feather",           "tre", ""           ],
    "bolt"             : ["Superstrong Stabilizer",      "tre", ""           ],
    "bolt_l"           : ["Repair Juggernaut",           "tre", ""           ],
    "castanets"        : ["Harmonic Synthesizer",        "tre", ""           ],
    "channel"          : ["Space Wave Receiver",         "tre", ""           ],
    "chess_king_black" : ["Joy Receptacle",              "tre", ""           ],
    "chess_king_white" : ["Worthless Statue",            "tre", ""           ],
    "chess_queen_black": ["Priceless Statue",            "tre", ""           ],
    "chess_queen_white": ["Triple Sugar Threat",         "tre", ""           ],
    "chocoichigo"      : ["Diet Doomer",                 "tre", ""           ],
    "chocoichigo_l"    : ["Drought Ender",               "tre", ""           ],
    "chocolate"        : ["King of Sweets",              "tre", ""           ],
    "chocolate_l"      : ["Enamel Buster",               "tre", ""           ],
    "chocowhite"       : ["Pale Passion",                "tre", ""           ],
    "chocowhite_l"     : ["White Goodness",              "tre", ""           ],
    "compact"          : ["Boom Cone",                   "tre", ""           ],
    "compact_make"     : ["Mirrored Stage",              "tre", ""           ],
    "cookie"           : ["Bug Bait",                    "tre", ""           ],
    "cookie_m_l"       : ["Imperative Cookie",           "tre", ""           ],
    "cookie_s"         : ["Comfort Cookie",              "tre", ""           ],
    "cookie_s_l"       : ["Succulent Mattress",          "tre", ""           ],
    "cookie_u"         : ["Compelling Cookie",           "tre", ""           ],
    "cookie_u_l"       : ["Impenetrable Cookie",         "tre", ""           ],
    "creap"            : ["Milk Tub",                    "tre", ""           ],
    "dashboots"        : ["Repugnant Appendage",         "tre", ""           ],
    "denchi_1_black"   : ["Thirst Activator",            "tre", ""           ],
    "denchi_1_red"     : ["Courage Reactor",             "tre", ""           ],
    "denchi_2_black"   : ["Durable Energy Cell",         "tre", ""           ],
    "denchi_2_red"     : ["Optical Illustration",        "tre", ""           ],
    "denchi_3_black"   : ["Fuel Reservoir",              "tre", ""           ],
    "denchi_3_red"     : ["Proton AA",                   "tre", ""           ],
    "dia_a_blue"       : ["Behemoth Jaw",                "tre", ""           ],
    "dia_a_green"      : ["Anxious Sprout",              "tre", ""           ],
    "dia_a_red"        : ["Citrus Lump",                 "tre", ""           ],
    "dia_b_blue"       : ["Luck Wafer",                  "tre", ""           ],
    "dia_b_green"      : ["Meat of Champions",           "tre", ""           ],
    "dia_b_red"        : ["Implement of Toil",           "tre", ""           ],
    "dia_c_blue"       : ["Boss Stone",                  "tre", ""           ],
    "dia_c_green"      : ["Strife Monolith",             "tre", ""           ],
    "dia_c_red"        : ["Talisman of Life",            "tre", ""           ],
    "diamond_blue"     : ["Regal Diamond",               "tre", ""           ],
    "diamond_blue_l"   : ["Tear Stone",                  "tre", ""           ],
    "diamond_green"    : ["Princess Pearl",              "tre", ""           ],
    "diamond_green_l"  : ["Crystal Clover",              "tre", ""           ],
    "diamond_red"      : ["Petrified Heart",             "tre", ""           ],
    "diamond_red_l"    : ["Eternal Emerald Eye",         "tre", ""           ],
    "doll"             : ["Silencer",                    "tre", ""           ],
    "donguri"          : ["Armored Nut",                 "tre", ""           ],
    "donguri_l"        : ["Corpulent Nut",               "tre", ""           ],
    "donutschoco"      : ["Chocolate Cushion",           "tre", ""           ],
    "donutschoco_s"    : ["Chance Totem",                "tre", ""           ],
    "donutsichigo"     : ["Sweet Dreamer",               "tre", ""           ],
    "donutsichigo_s"   : ["Dream Architect",             "tre", ""           ],
    "donutswhite"      : ["Cosmic Archive",              "tre", ""           ],
    "donutswhite_s"    : ["Spiny Alien Treat",           "tre", ""           ],
    "elec"             : ["Shock Therapist",             "tre", ""           ],
    "fire"             : ["Flare Cannon",                "tre", ""           ],
    "fire_helmet"      : ["Alien Billboard",             "tre", ""           ],
    "flask"            : ["Future Orb",                  "tre", ""           ],
    "flower_blue"      : ["Science Project",             "tre", ""           ],
    "flower_red"       : ["Cupid's Grenade",             "tre", ""           ],
    "fue_a"            : ["Brute Knuckles",              "tre", ""           ],
    "fue_b"            : ["Dream Material",              "tre", ""           ],
    "fue_pullout"      : ["Professional Noisemaker",     "tre", ""           ],
    "fue_wide"         : ["Amplified Amplifier",         "tre", ""           ],
    "futa_a_gold"      : ["Vorpal Platter",              "tre", ""           ],
    "futa_a_silver"    : ["Taste Sensation",             "tre", ""           ],
    "g_futa_daisen"    : ["Gherkin Gate",                "tre", ""           ],
    "g_futa_hirosima"  : ["Dimensional Slicer",          "tre", ""           ],
    "g_futa_hiruzen"   : ["Healing Cask",                "tre", ""           ],
    "g_futa_kajiwara"  : ["Survival Ointment",           "tre", ""           ],
    "g_futa_kitaama"   : ["Pondering Emblem",            "tre", ""           ],
    "g_futa_koiwai"    : ["Mysterious Remains",          "tre", ""           ],
    "g_futa_kyodo"     : ["Salivatrix",                  "tre", ""           ],
    "g_futa_kyosin"    : ["Yellow Taste Tyrant",         "tre", ""           ],
    "g_futa_kyusyu"    : ["Massive Lid",                 "tre", ""           ],
    "g_futa_nihonraku" : ["Activity Arouser",            "tre", ""           ],
    "g_futa_sakotani"  : ["Hypnotic Platter",            "tre", ""           ],
    "g_futa_sikoku"    : ["Happiness Emblem",            "tre", ""           ],
    "g_futa_titiyas"   : ["Creative Inspiration",        "tre", ""           ],
    "gas"              : ["Comedy Bomb",                 "tre", ""           ],
    "gear"             : ["Omega Flywheel",              "tre", ""           ],
    "gear_silver"      : ["Spirit Flogger",              "tre", ""           ],
    "gold_medal"       : ["Lustrous Element",            "tre", ""           ],
    "gum_tape"         : ["Superstick Textile",          "tre", ""           ],
    "gum_tape_s"       : ["Exhausted Superstick",        "tre", ""           ],
    "halloween"        : ["Possessed Squash",            "tre", ""           ],
    "haniwa"           : ["Gyroid Bust",                 "tre", ""           ],
    "hotate"           : ["Scrumptious Shell",           "tre", ""           ],
    "ichigo"           : ["Sunseed Berry",               "tre", ""           ],
    "ichigo_l"         : ["Combustion Berry",            "tre", ""           ],
    "j_block_blue"     : ["Favorite Gyro Block",         "tre", ""           ],
    "j_block_green"    : ["Lost Gyro Block",             "tre", ""           ],
    "j_block_red"      : ["Fond Gyro Block",             "tre", ""           ],
    "j_block_white"    : ["Treasured Gyro Block",        "tre", ""           ],
    "j_block_yellow"   : ["Memorable Gyro Block",        "tre", ""           ],
    "juji_key"         : ["Glee Spinner",                "tre", ""           ],
    "juji_key_fc"      : ["Stone of Glory",              "tre", ""           ],
    "kan"              : ["Decorative Goo",              "tre", ""           ],
    "kan_b_gold"       : ["Lip Service",                 "tre", ""           ],
    "kan_b_silver"     : ["Utter Scrap",                 "tre", ""           ],
    "kan_imuraya"      : ["Drone Supplies",              "tre", ""           ],
    "kan_iwate"        : ["Endless Repository",          "tre", ""           ],
    "kan_kyokuyo"      : ["Fruit Guard",                 "tre", ""           ],
    "kan_maruha"       : ["Stringent Container",         "tre", ""           ],
    "kan_meidiya"      : ["Nutrient Silo",               "tre", ""           ],
    "kan_nichiro"      : ["Patience Tester",             "tre", ""           ],
    "key"              : ["The Key",                     "tre", ""           ],
    "kinoko"           : ["Anti-hiccup Fungus",          "tre", ""           ],
    "kinoko_doku"      : ["Toxic Toadstool",             "tre", ""           ],
    "kinoko_tubu"      : ["Growshroom",                  "tre", ""           ],
    "kouseki_suisyou"  : ["Crystal King",                "tre", ""           ],
    "kumakibori"       : ["Fossilized Ursidae",          "tre", ""           ],
    "kuri"             : ["Seed of Greed",               "tre", ""           ],
    "leaf_kare"        : ["Disguised Delicacy",          "tre", ""           ],
    "leaf_normal"      : ["Love Nugget",                 "tre", ""           ],
    "leaf_yellow"      : ["Child of the Earth",          "tre", ""           ],
    "light_a"          : ["Stellar Orb",                 "tre", ""           ],
    "locket"           : ["Time Capsule",                "tre", ""           ],
    "loozy"            : ["King of Bugs",                "tre", ""           ],
    "makigai"          : ["Olimarnite Shell",            "tre", ""           ],
    "map01"            : ["Spherical Atlas",             "tre", ""           ],
    "map02"            : ["Geographic Projection",       "tre", ""           ],
    "matu_bokkuri"     : ["Conifer Spire",               "tre", ""           ],
    "medama_yaki"      : ["Hideous Victual",             "tre", ""           ],
    "milk_cap"         : ["Abstract Masterpiece",        "tre", ""           ],
    "mojiban"          : ["Mystical Disc",               "tre", ""           ],
    "momiji_kare"      : ["Onion Replica",               "tre", ""           ],
    "momiji_normal"    : ["Arboreal Frippery",           "tre", ""           ],
    "momiji_red"       : ["Infernal Vegetable",          "tre", ""           ],
    "nut"              : ["Adamantine Girdle",           "tre", ""           ],
    "nut_l"            : ["Massage Girdle",              "tre", ""           ],
    "otama"            : ["Merciless Extractor",         "tre", ""           ],
    "radar_a"          : ["Prototype Detector",          "tre", ""           ],
    "radar_b"          : ["Five-man Napsack",            "tre", ""           ],
    "robot_head"       : ["Remembered Old Buddy",        "tre", ""           ],
    "saru_head"        : ["Colossal Fossil",             "tre", ""           ],
    "sensya"           : ["Invigorator",                 "tre", ""           ],
    "silver_medal"     : ["Mirrored Element",            "tre", ""           ],
    "sinjyu"           : ["Memorial Shell",              "tre", ""           ],
    "sinkukan"         : ["Vacuum Processor",            "tre", ""           ],
    "sinkukan_b"       : ["Indomitable CPU",             "tre", ""           ],
    "sinkukan_c"       : ["Network Mainbrain",           "tre", ""           ],
    "suit_fire"        : ["Forged Courage",              "tre", ""           ],
    "suit_powerup"     : ["Justice Alloy",               "tre", ""           ],
    "tape_blue"        : ["Flame of Tomorrow",           "tre", ""           ],
    "tape_red"         : ["Furious Adhesive",            "tre", ""           ],
    "tape_yellow"      : ["Quenching Emblem",            "tre", ""           ],
    "tatebue"          : ["Directory of Destiny",        "tre", ""           ],
    "teala_dia_a"      : ["Essence of Rage",             "tre", ""           ],
    "teala_dia_b"      : ["Essence of Despair",          "tre", ""           ],
    "teala_dia_c"      : ["Essence of True Love",        "tre", ""           ],
    "teala_dia_d"      : ["Essence of Desire",           "tre", ""           ],
    "tel_dial"         : ["Nouveau Table",               "tre", ""           ],
    "toy_cat"          : ["Wiggle Noggin",               "tre", ""           ],
    "toy_dog"          : ["Sud Generator",               "tre", ""           ],
    "toy_gentle"       : ["Manual Honer",                "tre", ""           ],
    "toy_lady"         : ["Broken Food Master",          "tre", ""           ],
    "toy_ring_a_blue"  : ["Frosty Bauble",               "tre", ""           ],
    "toy_ring_a_green" : ["Gemstar Husband",             "tre", ""           ],
    "toy_ring_a_red"   : ["Pink Menace",                 "tre", ""           ],
    "toy_ring_b_blue"  : ["Universal Com",               "tre", ""           ],
    "toy_ring_b_green" : ["Joyless Jewel",               "tre", ""           ],
    "toy_ring_b_red"   : ["Gemstar Wife",                "tre", ""           ],
    "toy_ring_c_blue"  : ["Icon of Progress",            "tre", ""           ],
    "toy_ring_c_green" : ["Innocence Lost",              "tre", ""           ],
    "toy_ring_c_red"   : ["Fleeting Art Form",           "tre", ""           ],
    "toy_teala"        : ["Unspeakable Wonder",          "tre", ""           ],
    "turi_uki"         : ["Aquatic Mine",                "tre", ""           ],
    "uji_jisyaku"      : ["Heavy-Duty Magnetizer",       "tre", ""           ],
    "wadou_kaichin"    : ["Unknown Merit",               "tre", ""           ],
    "watch"            : ["Temporal Mechanism",          "tre", ""           ],
    "water"            : ["Monster Pump",                "tre", ""           ],
    "whistle"          : ["Emperor Whistle",             "tre", ""           ],
    "yoyo_blue"        : ["Impediment Scourge",          "tre", ""           ],
    "yoyo_red"         : ["Flame Tiller",                "tre", ""           ],
    "yoyo_yellow"      : ["Doomsday Apparatus",          "tre", ""           ],
}
